version: 2.1
executors:
  tfupdate:
    docker:
      - image: minamijoyo/tfupdate:latest

jobs:
  tfupdate_terraform:
    executor: tfupdate
    steps:
      - checkout
      - run:
          name: Show tfupdate version
          command: |
            tfupdate --version
      - run:
          name: Update terraform to latest
          command: |
            tfupdate terraform ./
      - run:
          name: Check git diff
          command: |
            git diff

workflows:
  version: 2
  update:
    jobs:
      - tfupdate_terraform
