version: 2.1
executors:
  tfupdate:
    docker:
      - image: minamijoyo/tfupdate:latest

jobs:
  tfupdate_terraform:
    executor: tfupdate
    steps:
      - checkout
      - run:
          name: Show tfupdate version
          command: |
            tfupdate --version
      - run:
          name: Setup git config
          command: |
            git config --local user.name 'tfupdate-circleci'
            git config --local user.email 'minamijoyo+tfupdate-circleci@gmail.com'
            echo "https://${GITHUB_TOKEN}:@github.com" > $HOME/.config/git-credential
            git config --local credential.helper "store --file=$HOME/.config/git-credential"
      - run:
          name: Update terraform to latest
          command: |
            VERSION=$(tfupdate release latest hashicorp/terraform)
            git checkout -b update-terraform-to-v${VERSION}
            tfupdate terraform -v ${VERSION} ./
            git add . && git diff --cached --exit-code --quiet || git commit -m "Update terraform to v${VERSION}"
            hub pr list -f "%t" | grep "Update terraform to v${VERSION}" || (git push origin HEAD && hub pull-request -m "Update terraform to v${VERSION}")

workflows:
  version: 2
  update:
    jobs:
      - tfupdate_terraform
