version: 2.1
executors:
  tfupdate:
    docker:
      - image: minamijoyo/tfupdate:latest

commands:
  git_config:
    description: Setup git config
    parameters:
      user_name:
        description: git user name
        type: string
      user_email:
        description: git user email
        type: string
      github_token:
        description: environment variable name for GitHub access token
        type: env_var_name
        default: GITHUB_TOKEN
    steps:
      - run:
          name: Setup git config
          command: |
            git config --local user.name << parameters.user_name >>
            git config --local user.email << parameters.user_email >>
            mkdir -p $HOME/.config
            echo "https://${<< parameters.github_token >>}:@github.com" > $HOME/.config/git-credential
            git config --local credential.helper "store --file=$HOME/.config/git-credential"
            git config --local url."https://github.com/".insteadOf 'git@github.com:'
  tfupdate_terraform:
    description: Update the terraform to latest
    parameters:
      args:
        description: Arguments for tfupdate command
        type: string
        default: ./
    steps:
      - run:
          name: Update the terraform to latest
          command: |
            VERSION=$(tfupdate release latest hashicorp/terraform)
            UPDATE_MESSAGE="Update terraform to v${VERSION}"
            if hub pr list -f "%t: %U" | grep "$UPDATE_MESSAGE"; then
              echo "A pull request already exists"
            else
              git checkout -b update-terraform-to-v${VERSION}
              tfupdate terraform -v ${VERSION} << parameters.args >>
              if git add . && git diff --cached --exit-code --quiet; then
                echo "No changes"
              else
                git commit -m "$UPDATE_MESSAGE"
                git push origin HEAD && hub pull-request -m "$UPDATE_MESSAGE"
              fi
            fi
  tfupdate_provider:
    description: Update a provider to latest
    parameters:
      args:
        description: Arguments for tfupdate command
        type: string
        default: ./
      provider_name:
        description: A name of provider
        type: string
    steps:
      - run:
          name: Update a provider to latest
          command: |
            VERSION=$(tfupdate release latest terraform-providers/terraform-provider-<< parameters.provider_name >>)
            UPDATE_MESSAGE="Update terraform-provider-<< parameters.provider_name >> to v${VERSION}"
            if hub pr list -f "%t: %U" | grep "$UPDATE_MESSAGE"; then
              echo "A pull request already exists"
            else
              git checkout -b update-terraform-provider-<< parameters.provider_name >>-to-v${VERSION}
              tfupdate provider << parameters.provider_name >> -v ${VERSION} << parameters.args >>
              if git add . && git diff --cached --exit-code --quiet; then
                echo "No changes"
              else
                git commit -m "$UPDATE_MESSAGE"
                git push origin HEAD && hub pull-request -m "$UPDATE_MESSAGE"
              fi
            fi

jobs:
  tfupdate:
    executor: tfupdate
    steps:
      - checkout
      - run: tfupdate --version
      - git_config:
          user_name: 'tfupdate-circleci'
          user_email: 'minamijoyo+tfupdate-circleci@gmail.com'
      - tfupdate_terraform
      - tfupdate_provider:
          provider_name: 'aws'

workflows:
  version: 2
  update:
    jobs:
      - tfupdate
