version: 2.1
executors:
  tfupdate:
    docker:
      - image: minamijoyo/tfupdate:latest

commands:
  git_config:
    description: Setup git config
    parameters:
      user_name:
        description: git user name
        type: string
      user_email:
        description: git user email
        type: string
      github_token:
        description: environment variable name for GitHub access token
        type: env_var_name
        default: GITHUB_TOKEN
    steps:
      - run:
          name: Setup git config
          command: |
            git config --local user.name << parameters.user_name >>
            git config --local user.email << parameters.user_email >>
            mkdir -p $HOME/.config
            echo "https://${<< parameters.github_token >>}:@github.com" > $HOME/.config/git-credential
            git config --local credential.helper "store --file=$HOME/.config/git-credential"
            git config --local url."https://github.com/".insteadOf 'git@github.com:'
  tfupdate_terraform:
    description: Update terraform to latest
    steps:
      - run:
          name: Update terraform to latest
          command: |
            VERSION=$(tfupdate release latest hashicorp/terraform)
            UPDATE_MESSAGE="Update terraform to v${VERSION}"
            git checkout -b update-terraform-to-v${VERSION}
            tfupdate terraform -v ${VERSION} ./
            git add . && git diff --cached --exit-code --quiet || git commit -m "$UPDATE_MESSAGE"
            hub pr list -f "%t" | grep "$UPDATE_MESSAGE" || (git push origin HEAD && hub pull-request -m "$UPDATE_MESSAGE")

jobs:
  tfupdate:
    executor: tfupdate
    steps:
      - checkout
      - run: tfupdate --version
      - git_config:
          user_name: 'tfupdate-circleci'
          user_email: 'minamijoyo+tfupdate-circleci@gmail.com'
      - tfupdate_terraform

workflows:
  version: 2
  update:
    jobs:
      - tfupdate
